// This is a placeholder file which shows how you can define functions which can be used from both a browser script and a node script. You can delete the contents of the file once you have understood how it works.

// export function getGreeting() {
//     return "Hello";
// }

//steps 
// fetch data from days
// display data on page to make sure they working 


// 1 . Create an HTML page which, when loaded, displays a calendar. Done

// 2. The calendar must show every day of the current month, each as a rectangle. Done
// Each row of rectangles must show one week. The first column must show Mondays. 
// The first day of the month must be shown in the first row.

// 3. There must be two buttons which, when clicked, switch what is displayed. 
// One button must change the display to the previous month. The other button must change the display to the next month. 
// On repeated clicks, these buttons must keep moving back/forwards in time, one month per click.

// 4. There must be a way to jump to a particular month and year, e.g. “October 2020”. 
// For example, you could use a <select> tag for each of the month name and a reasonable range of years.

// 5. The days from the JSON file must appear correctly when the month they fall in is displayed. For example:
// If October 2024 is being shown, October 8th must show Ada Lovelace Day.
// If October 2025 is being shown, October 14th must show Ada Lovelace Day.

// 6. The calendar should work for every year - if someone goes to 1900, or 2050, 
// or any other year, the commemerative days should be correctly displayed.
// The calendar must be dynamically generated by reading the JSON file. 
// You must not hard-code any days in the HTML file.
// Other than the above styling requirements, no styling is required.